### ISSUE TITLE
Typo on Home Page

### ISSUE THREAD

**Issue by ahenkels** [empowerhack/empowerhack.github.io#27]
1) There is a typo on the home page. Right now it says "EmpowerHack is a collective that brings creates sustainable design..." we need to remove "brings" 
<img width="1032" alt="screen shot 2016-04-07 at 7 23 30 pm" src="https://cloud.githubusercontent.com/assets/12966192/14362228/7bd64ccc-fcf6-11e5-8082-8abbfe0ad675.png">

2) The link to HaBaby (http://hababy.empowerhack.io/index.html) doesn't work
<img width="1223" alt="screen shot 2016-04-07 at 7 25 35 pm" src="https://cloud.githubusercontent.com/assets/12966192/14362249/8e7f49c8-fcf6-11e5-8e1b-894451045b01.png">

**Comment by eddiejaoude** [comment]
Point 2 has been moved to here https://github.com/empowerhack/Hababy-Website/issues/5

**Comment by varun-ramraj** [comment]
Should this ticket be closed, or is there anything else to do for it? Happy to help if needed. :)

**Comment by eddiejaoude** [comment]
I think the typo has been fixed? @ahenkels can you clarify please? Then we can close the ticket and focus on the next ones.

**Comment by ahenkels** [comment]
Yes, looks like the typo has been fixed.

**Comment by eddiejaoude** [comment]
Ok, thanks, I am going to close
