### ISSUE TITLE
Redirect blog.empowerhack.com to blog.empowerhack.io

### ISSUE THREAD

**Issue by eddiejaoude** [empowerhack/empowerhack.github.io#9]
Dependent on #6 - wait until it is completed first

**Comment by eddiejaoude** [comment]
#6 is now complete, @atmostat please can you redirect http://blog.empowerhack.com to http://blog.empowerhack.io

**Comment by atmostat** [comment]
Done.

**Comment by eddiejaoude** [comment]
Awesome, thanks!
